[package]
name = "mio-serial"
version = "0.2.0"
authors = ["Zac Berkowitz <zac.berkowitz@gmail.com>"]
description = "A serial port implementation for mio"
license = "MIT"
homepage = "https://github.com/berkowski/mio-serial"
repository = "https://github.com/berkowski/mio-serial"
documentation = "http://docs.rs/mio-serial"
readme = "README.md"
keywords = ["rs232", "serial", "mio"]
categories = ["asynchronous", "hardware-support"]

[dependencies]
mio = "0.6"
libc = "0.2"
serialport = "0.9"

[target.'cfg(unix)'.dependencies]
termios = "0.2"

[target.'cfg(windows)'.dependencies]
lazycell = "0.5.0"

[[example]]
name = "serial_printline"
path = "examples/serial_printline.rs"
